@startuml
title Colaboracion - Iteracion 3: gesto reconocido o no
left to right direction
object Persona
object Gesto
object Observador
object Aura
Persona --> Gesto : 1. hace
Gesto --> Observador : 2. es visto por
Observador --> Aura : 3 [reconocido]. otorga
Aura --> Persona : 4 [reconocido]. le da
Observador --> Persona : 3a [no reconocido]. no gana aura
@enduml
